<a href="https://colab.research.google.com/github/umamaparveen/Data-science-/blob/main/DS_Batch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Python

In [ ]:
# @title Comments
# Single Line Comment
'''
Multi Line Comment
Adding two numbers and storing the value in sum (This statment will be completly ignored by python)
Press CTRL + Enter to run the program
'''
a = 2
b = 3
sum = a + b
print(sum)

5


# Print Function

In [ ]:
# print function
# Syntax for Print function
print() # correct syntax
Print() # Wrong Syntax

In [ ]:
print('Hello World') # Valid Syntax
print("Hello World") # Valid Syntax
n1 = 10
n2 = 20
sum = n1 + n2
print(sum) # Valid Syntax to print the value of sum
print('sum')

Hello World
Hello World
30
sum


In [ ]:
# There are two parameters in print function
'''
1) end parameter
2) sep parameter
'''
# Print both statments in a single line
print('Hello world', end = '\n') #Default value of end is '\n'(new line)
print('How are You?')
# Seperate two staments with @
print('rinex','gmail.com', sep = '@') # Default value of sep is ' ' (Space)

Hello world
How are You?
rinex@gmail.com


# Variable

In [ ]:
# Anything that can store any value in programming language is termed as variable
a = 10 # Here a is a variable
message = 'Hello World' # Here message is a variable
print(a)
print(message)
'''
Rules to write a variable
1) You cannot start the variable name with a number but you continue with it.
Ex : 1a - Invalid , a1 - Valid
2) We cannot use keywords as variable name.
Ex : print = 10 (Invalid)
3) Case sensitive
Ex :
a = 10
print(A) # Invalid syntax
a = 10
print(a) # Valid Syntax
'''

10
Hello World


'\nRules to write a variable\n1) You cannot start the variable name with a number but you continue with it.\nEx : 1a - Invalid , a1 - Valid\n2) We cannot use keywords as variable name.\nEx : print = 10 (Invalid)\n3) Case sensitive\nEx :\na = 10\nprint(A) # Invalid syntax\na = 10\nprint(a) # Valid Syntax\n'

# BASIC OPERATORS IN PYTHON

1) Arithmetic Operators

2) Comparison Operators

3) Logical Operators

4) Assignment Operators

In [ ]:
# @title Arithmetic Operators
'''
1) Addition (+)
2) Subtraction (-)
3) Division (/)
4) Multiplication (*)
5) Modulus (Remainder) (%)
6) Floor Division (//)
7) Exponent (**)
'''
a = 10
b = 5
sum = a + b
print("Sum is", sum)
diff = a - b
print("Difference is", diff)
qnt = a / b
print("Quotient is", qnt)
prod = a * b
print("PRoduct is", prod)

num1 = 5
num2 = 2
qnt = num1 / num2
print("Quotient is", qnt)
rem = num1 % num2
print("Remainder is", rem)
qnt_without_decimal = num1 // num2
print("Quotient without Decimal point", qnt_without_decimal)
pow = 5 ** 2 #This means 5 to the power 2
print(pow)

Sum is 15
Difference is 5
Quotient is 2.0
PRoduct is 50
Quotient is 2.5
Remainder is 1
Quotient without Decimal point 2
25


In [ ]:
# @title Comparison Operators
'''
1) Equal to (==)
2) Not Equal (!=)
3) Greater than (>)
4) Greater than or equal to (>=)
5) Lesser than (<)
6) Lesser than or equal to (<=)
'''
ex1 = (1 == 1)
print(ex1)
ex2 = (1 != 1)
print(ex2)
ex3 = (5 > 15)
print(ex3)
ex4 = (5 >= 5)
print(ex4)

True
False
False
True


In [ ]:
# @title Logical Operators
'''
1) Logical AND (and)
2) Logical OR (or)
3) Logical NOT (not)
'''
ex1 = (10 > 2) and (2 > 1) # If we use and operator both conditions should be True
print(ex1)
ex2 = (1 > 2) or (2 > 1) # If any one condition is True then the output is True
print(ex2)
ex3 = not False
print(ex3)

True
True
True


In [ ]:
# @title Assigment Operators
'''
0) Assignment (=)
1) Addition Assigment(+=)
2) Subtraction Assigment(-=)
3) Division Assigment(/=)
4) Multiplication Assigment(*=)
5) Modulus Assigment(Remainder) (%=)
6) Floor Division Assigment(//=)
7) Exponent Assigment(**=)
'''
ex1 = 5
#print(ex1)
ex1 += 5 #ex1 = ex1 + 5
print(ex1)
ex2 = 10
ex2 *= 5#ex2 = ex2 * 5
print(ex2)
ex3 = 5
ex3 **= 2 # ex3 = ex3 ** 2
print(ex3)

10
50
25


# CONDITIONAL STATMENT

1) IF statement

2) IF else Statement

3) IF elif else Statement

# Datatypes

In [ ]:
# @title Example 1
# Check if the number is greater than 0 or not.
num = int(input('Enter the Number'))
if num > 0:
  print("Number is greater than 0")
elif num == 0:
  print("Number is equal to 0")
else:
  print("Number is lesser than 0")

Enter the Number7
Number is greater than 0


In [ ]:
# @title Example 2
# Check if the number is +ve or -ve
num = int(input("Enter the Number"))
if num > 0:
  print("+ve")
elif num == 0:
  print("Number is Zero")
else:
  print("-ve")

Enter the Number0
Number is Zero


In [ ]:
# @title Example 3
# Check if you are admin, then you have admin privilege else you have no access
admin_input = input("Enter admin username")
username = 'admin'
if admin_input == username:
  print("You have Admin Privilege")
  password = input("Enter you password")
  if password == '123456':
    print("Password Match Sucessful")
  else:
    print("Invalid Password")
else:
  print("Inavlid Username")

Enter admin usernameadmin
You have Admin Privilege
Enter you password123456
Password Match Sucessful


In [ ]:
# @title Example 4
# Check if you user is eligible to vote (Age >= 18)
age = int(input("Enter your age"))
if age >= 18:
  print("Eligible to Vote")
else:
  print("Not Eligible to Vote")

Enter your age18
Eligible to Vote


In [ ]:
# @title Example 5
# If a student scores more than 90 then Grade A, else marks more than 80 then Grade B, 70 then Grade C else fail
marks = float(input("Enter the marks"))
if marks >= 90:
  print("Grade A")
elif marks >= 80:
  print("Grade B")
elif marks >= 70:
  print("Grade C")
else:
  print("Fail")

Enter the marks99.9
Grade A


In [ ]:
# @title Example 6
# Check if the number is divisible by 7
num = int(input("Enter the Number"))
if num % 7 == 0:
  print("Divisible by 7")
else:
  print("Not Divisible by 7")

Enter the Number48
Not Divisible by 7


# Exercise

In [ ]:
# Exercise 1
# If the employee is working in the company for more than 5 years then he/she will get a bonus of 50% to thier current salary
yoe = int(input("Enter year of experience"))
if yoe > 5:
  salary = float(input("Enter salary"))
  bonus = salary * 0.5
  print(f'Your current salary is {salary} and bonus is {bonus}. Total payout {salary + bonus}')
else:
  print("No bonus")

Enter year of experience3
No bonus


In [ ]:
# Exercise 2
# If the electricty units is less than 100 then no charge, else if the electricity unit is greater than 100 and lesser than
# 200 then Rs.10 per unit. If the units is greater than 200 then Rs.15 per unit
units = float(input("Enter the no.of units"))
if units < 100:
  print("No Charge")
elif units < 200:
  print("Charges will be", (units - 100) * 10)
else:
  print("Charges will be", (units - 200) * 15 + (units - 100) * 10)

Enter the no.of units201
Charges will be 1025.0


In [ ]:
# Exercise 3
# Find whether the character is a vowel or a consonant
char = input("Enter any letter")
print(type(char))
char_lower = char.lower()
vowels = ['a','e','i','o','u']
if char_lower in vowels:
  print("Given Letter is a Vowel")
else:
  print("Given letter is a Consonant")

'5'

Enter any letter5
<class 'str'>
Given letter is a Consonant


In [ ]:
# Exercise 4
# BMI Calculator
# BMI = (Weight(KG)) / (Height(M) ** 2)
# BMI < 18.5 Then Underweight
# BMI between 18.5 and 24.9 then normal weight
# BMI between 24.9 and 29.9 then overweight
# BMI > 29.9 Obese
weight = float(input("Enter weight in Kgs"))
height = float(input("Enter height in meters"))
BMI = weight / (height ** 2)
if BMI < 18.5:
  print(f"BMI Score is {BMI} Underweight")
  #print("BMI Score is",BMI,"Underweight")
elif BMI >= 18.5 and BMI < 24.9:
  print(f"BMI Score is {BMI} Normal Weight")
elif BMI >= 24.9 and BMI < 29.9:
  print(f"BMI Score is {BMI} Over Weight")
else:
  print("Obese")

Enter weight in Kgs65
Enter height in meters1.71
BMI Score is 22.229061933586404 Normal Weight


In [ ]:
# Exercise 5
database = {
    'user1':'123456',
    'user2':'654321',
    'user3':'123@abc',
    'user4':'654@123'
}
username = input("Enter your username")
if username in database.keys():
  password = input("Enter your password")
  if password in database[username]:
    print("Welcome", username)
  else:
    print("Invalid password")
else:
  print("Invalid Username")

Enter your usernameuser1
Enter your password123456
Welcome user1


In [ ]:
# @title Looping Statements
'''
1) For loop (Whenever we know the no.of iterations)
2) While loop (Whenever we do not know the no.of iterations) - Infinite loop
'''

'123456'

In [ ]:
# Syntax of using a for loop
for i in codintion:
  staments

In [ ]:
# Using for loop to print 'Hello World' 10 times
for i in range(0,10): # i = 0
  print("Hello World")

Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World


In [ ]:
# Range Function syntax
'''
range(start,stop-1,step-size):
start default value is 0
step-size value will be +1 by default
'''

In [ ]:
# Using for loop print values from 0 to 10
for i in range(0,11): # i = i + 1
  print(i) # i = 0

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
# Using for loop print values from 11 to 20
for i in range(11,21):
  print(i)

11
12
13
14
15
16
17
18
19
20


In [ ]:
# Using for loop print values that are divisible by 2 from 0 to 20
for i in range(0,21,2):
  print(i)

0
2
4
6
8
10
12
14
16
18
20


In [ ]:
# Print values from 10 to 1
for i in range(10,0,-1):
  print(i)

10
9
8
7
6
5
4
3
2
1


In [ ]:
'''
*
*
*
*
*
'''
for i in range(5):
  print("*")

*
*
*
*
*


In [ ]:
'''
* * * * *
'''
for i in range(5):
  print("*", end = " ")

* * * * * 

In [ ]:
# Syntax for While loop
'''
initializattion_variable = value
while conditions:
  statements
  icrement/decrement
'''
# Example to print hello world 10 times
i = 0
while i < 10:
  print("Hello World")
  i += 1 # Addition assignment

Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World


In [ ]:
# Using while loop print 0 to 10
i = 0
while i < 11:
  print(i)
  i += 1

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
# Using while loop print 0 to 20 with multiples of 2
i = 2
while i < 21:
  print(i)
  i += 2

2
4
6
8
10
12
14
16
18
20


In [ ]:
# Using while loop print 20 to 0
i = 20
while i >= 0:
  print(i)
  i -= 1

20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0


In [ ]:
'''
*
*
*
*
*
'''
i = 0
while i < 5:
  print("*")
  i += 1

*
*
*
*
*


In [ ]:
'''
* * * * *
'''
i = 0
while i < 5:
  print("*", end = " ")
  i += 1

* * * * * 

In [ ]:
print(' 1) Addition\n 2) Subtraction\n 3) Division\n 4) Multiplication\n 5) Quit')
while True:
  choice = int(input("Enter your choice"))
  if choice > 0 and choice < 5:
    num1 = int(input("Enter number 1"))
    num2 = int(input("Enter number 2"))
    if choice == 1:
      print("Sum is", num1 + num2)
    elif choice == 2:
      print("Difference is", num1 - num2)
    elif choice == 3:
      print("Quotient is", num1 / num2)
    elif choice == 4:
      print("Product is", num1 * num2)
  elif choice == 5:
    print("Thank you")
    break
  else:
    print("Invalid choice")

 1) Addition
 2) Subtraction
 3) Division
 4) Multiplication
 5) Quit
Enter your choice6
Invalid choice
Enter your choice5
Thank you


# Function

In [ ]:
# In Python, a function is a reusable block of code that perform a specific task or a set of tasks.
# Syntax
def function_name(parameters):
  # Function body
  # Code to perform a specific task
  # Returm statement

In [ ]:
# @title Example 1
# Code to return whether the given number is odd or even
#File - oddeve
def oddeve(x):
  if x == 0:
    print("Number is 0")
  elif x % 2 != 0:
    print("Odd")
  else:
    print("Even")

In [ ]:
oddeve(0)

Number is 0


In [ ]:
# Exercise 2
# If the employee is working in the company for more than 5 years then he/she will get a bonus of 50% to thier current salary
def bonus():
  yoe = int(input("Enter year of experience"))
  if yoe > 5:
    salary = float(input("Enter salary"))
    bonus = salary * 0.5
    print(f'Your current salary is {salary} and bonus is {bonus}. Total payout {salary + bonus}')
  else:
    print("No bonus")

In [ ]:
# @title Lambda Function
'''
def add(x,y):
  sum = x + y
  print('Sum is', sum)

add(5,4)
'''
add = lambda x,y : x + y
add(5,4)

9

# NumPy (Numerical Python)

In [ ]:
# NumPy stands for Numerical python.
# NumPy is a python library used for working with arrays.
# Arrays is collection of objects.

In [ ]:
# @title Steps to follow
# Step 1: Import numpy library
import numpy as np
# Step 2: Convert list into a array
x = [1,2,3]
arr = np.array(x)
# Step 3: Conditions
print("Finding sqaares of each array element", arr ** 2)

Finding sqaares of each array element [1 4 9]


In [ ]:
# @title Example 1
# Add +1 to each list elements
x = [1,2,3,4,5]
import numpy as np
arr = np.array(x)
print(1)

[2 3 4 5 6]


In [ ]:
# @title Example 2
# Mathematical Operations using Numpy
x = [5,1,4,9]
arr = np.array(x)
print("Mathematical Operations on the array", arr % 2)

Mathematical Operations on the array [1 1 0 1]


In [ ]:
# @title Example 3
# Converting a list into an array without declaring the list
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
# Find maximum value out of array 1
max_val = np.max(arr1)
print("Max value of array 1 is", max_val)
min_val = np.min(arr2)
print("Minimum value of array 2 is", min_val)
avg_val = np.mean(arr2)
print("Average value of array 2 is", avg_val)

Max value of array 1 is 5
Minimum value of array 2 is 6
Average value of array 2 is 8.0


In [ ]:
# @title Example 4
# Find the dimension of the array
x = [1,2,3,4,5]
arr = np.array(x)
print(arr.ndim)

1


In [ ]:
# @title Example 5
# Create 2D array
x = [[1,2,3],[4,5,6]]
arr = np.array(x)
print(arr.ndim)

2


In [ ]:
# @title Steps to create multi dimensional arrays
# Step 1: Create Outermost array
x = []
# Step 2: Create Inner Array
x = [[],[]]
# Step 3: Create Inner most array
x = [[[],[]],[[],[]]]

In [ ]:
# @title Random Number Library
# Exploring random number library from numpy
import numpy as np
from numpy import random
x = (random.randint(10))
arr = np.array(x)
print(arr)

59


In [ ]:
# @title Example 1
# Create 1D array using random library
x = (random.randint(10, size =(5)))
arr = np.array(x)
print(arr)

[0 1 9 1 3]


In [ ]:
# @title Example 2
# Create 2D array using random library
x = (random.randint(10, size =(5, 3)))
arr = np.array(x)
print(arr)

[[9 0 3]
 [8 8 5]
 [4 3 9]
 [8 7 3]
 [3 9 1]]


In [ ]:
# @title Example 3
# Create 3D array using random library
x = (random.randint(10, size =(5,3,3)))
arr = np.array(x)
print(arr.ndim)

3


In [ ]:
# @title A-range function
'''
It is similar to range function but returns array
'''
import numpy as np
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# @title Example 1
# Change the datatype
x = np.arange(1,11, dtype = float)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# @title Example 2
# Specifying the start and end value
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# @title Example 3
# Print array containing zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# @title Example 4
# Print array containing ones
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# @title Example 5
# Print 2D array containing zeros
x = np.zeros([2,4], dtype = int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# @title Example 6
# Print Identity Matrix
np.identity(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# @title Example 7
np.eye(4,k = -2, dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [ ]:
# Convert 1D array into 2D array
x = np.arange(20)
print("Original array",x)
print("Original array dimension", x.ndim)
'''
Factors of 20
1,20
20,1
2,10
10,2
4,5
5,4
'''
reshaped = x.reshape(5,-1)
print("Reshaped array",reshaped)
print("Reshaped array dimension", reshaped.ndim)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Original array dimension 1
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Reshaped array dimension 2


In [ ]:
# Convert 1D array into 3D array
x = np.arange(20)
print("Original array",x)
print("Original array dimension", x.ndim)
'''
Factors of 20
1,5,2,2
5,2,1
2,5,2
5,2,2
2,2,5
5,2,2
'''
reshaped = x.reshape(2,2,5)
print("Reshaped array",reshaped)
print("Reshaped array dimension", reshaped.ndim)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Original array dimension 1
Reshaped array [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
Reshaped array dimension 3


In [ ]:
# Convert 1D array into 3D array
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original array",x)
print("Original array dimension", x.ndim)
'''
Factors of 10
1,2,5
5,2,1
2,5,1
1,5,2
10,1,1
1,1,10
5,1,2
'''
reshaped = x.reshape(2,5,1)
print("Reshaped array",reshaped)
print("Reshaped array dimension", reshaped.ndim)

Original array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Original array dimension 2
Reshaped array [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
Reshaped array dimension 3


In [ ]:
x = np.array([[[1,2,3,4,5]],[[6,7,8,9,10]]])
print(x.ndim)
# 3D - 1D array
'''
2,5,1
'''
reshape = x.reshape(10)
print(reshape)
print(reshape.ndim)
# 3D - 2D array
'''
2,5
5,2
10,1
1,10
'''
reshape = x.reshape(5,-1)
print(reshape)
print(reshape.ndim)


3
[ 1  2  3  4  5  6  7  8  9 10]
1
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


In [ ]:
# @title Accessing Array Elements
'''
1) Slicing
2) Integer Array Indexing
3) Boolean Array Indexing
'''

In [ ]:
# Slicing
import numpy as np
arr1 = np.array([1,2,3])
print(arr1[0])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1][1])

1
5


In [ ]:
# Integer Array Indexing
arr1 = np.array([1,2,3,4,5])
print(arr1[2])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1,2])

3
6


In [ ]:
# Boolean Array Indexing
arr = np.array([[32,5,23,1,43,12,34,34,345,23,23],
                [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which are greater than 70")
cond = (arr > 70)
print(arr[cond])

Extract only those values which are greater than 70
[345  76  76  87]


In [ ]:
arr = np.array([[32,5,23,1,43,12,34,34,345,23,23],
                [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which are not divisible by 2 or basically extract odd numbers")
cond = (arr % 2 != 0) # != Not equal to
print(arr[cond])

Extract only those values which are not divisible by 2 or basically extract odd numbers
[  5  23   1  43 345  23  23  23  23  87]


In [ ]:
# @title Student Report Dataset
import numpy as np
students_array = np.array([['Student_1', 59, 64, 94, 87, 81],

                          ['Student_2', 8, 56, 18, 58, 69],

                          ['Student_3', 7, 20, 60, 63, 42],

                          ['Student_4', 71, 94, 71, 68, 13],

                          ['Student_5', 89, 1, 16, 33, 40],

                          ['Student_6', 4, 25, 48, 41, 84],

                          ['Student_7', 3, 79, 46, 9, 71],

                          ['Student_8', 87, 77, 75, 15, 69],

                          ['Student_9', 61, 1, 48, 98, 23],

                          ['Student_10', 98, 60, 24, 66, 56],

                          ['Student_11', 58, 12, 75, 7, 98],

                          ['Student_12', 23, 62, 6, 35, 37],

                          ['Student_13', 14, 25, 87, 56, 8],

                          ['Student_14', 68, 1, 81, 11, 61],

                          ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [ ]:
# @title Task 1
# Accessing all the names of the students
students_array[:,0] # [rows, columns]

array(['Student_1', 'Student_2', 'Student_3', 'Student_4', 'Student_5',
       'Student_6', 'Student_7', 'Student_8', 'Student_9', 'Student_10',
       'Student_11', 'Student_12', 'Student_13', 'Student_14',
       'Student_15'], dtype=object)

In [ ]:
# @title Task 2
# Find the average of subject 1
method1 = np.mean(students_array[:,1])
method2 = students_array[:,1].mean()
print(method1, method2)

44.06666666666667 44.06666666666667


In [ ]:
# @title Task 3
# Find the average of subject 4
students_array[:,3].mean()

np.float64(52.266666666666666)

In [ ]:
# @title Task 4
# Find the average of student 7
students_array[6,1:].mean()

np.float64(41.6)

In [ ]:
# @title Task 5
# Find the average of student 7 for subject 2 to 4
students_array[6,2:5].mean()

np.float64(44.666666666666664)

In [ ]:
# @title Task 6
# Find the count of students where subject 1 marks is greater than subject 2 marks
sub1 = students_array[:,1]
sub2 = students_array[:,2]
cond = sub1 > sub2
print("No.of students who scored subject1 marks greater than subject 2 marks are", len(students_array[cond]))

No.of students who scored subject1 marks greater than subject 2 marks are 6


In [ ]:
# @title Task 7
# Find the student average of first 10 students
sub_avg = students_array[:10,1:]
print(sub_avg.mean(axis = 1)) # Row wise average
#print(sub_avg.mean(axis = 0)) # Column wise average

[77.0 41.8 38.4 63.4 35.8 40.4 41.6 64.6 46.2 60.8]


In [ ]:
# @title Task 8
# Find the Subject average of 1,3 and 4 subject.
sub_avg = students_array[:,[1,3,4]]
print(sub_avg.mean(axis = 0))

[44.06666666666667 52.266666666666666 44.266666666666666]


In [ ]:
# @title Task 9
# Find the subject average of student 5 to student 14
sub_avg = students_array[5:15,1:].mean(axis = 0)
print(sub_avg)

[42.7 41.1 52.5 35.5 57.3]


In [ ]:
# @title Task 10
# Find all the student names who scored higher than student 15 in both subject1 and subject2
stu15_sub1_marks = students_array[14,1]
stu15_sub2_marks = students_array[14,2]
sub1 = students_array[:,1]
sub2 = students_array[:,2]
cond1 = sub1 > stu15_sub1_marks
cond2 = sub2 > stu15_sub2_marks
merged_cond = cond1 & cond2
print(students_array[merged_cond,0])

['Student_4' 'Student_8']


In [ ]:
# @title Task 11
# Find all the student names who scored higher than student 11 either in subject 1 or subject 5
stu11_sub1_marks = students_array[10,1]
stu11_sub5_marks = students_array[10,5]
sub1 = students_array[:,1]
sub5 = students_array[:,5]
cond1 = sub1 > stu11_sub1_marks
cond2 = sub5 > stu11_sub5_marks
merged_cond = cond1 | cond2
print(students_array[merged_cond,0])

['Student_1' 'Student_4' 'Student_5' 'Student_8' 'Student_9' 'Student_10'
 'Student_14']


In [ ]:
# @title Bank Customer Dataset
# Age , Employment , Marital Status, Balance, Personal Loan, Car Loan, Connection, Month of Join
import numpy as np
banking_array = np.array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular','oct'],

       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular','may'],

       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular','apr'],

       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown','jun'],

       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown','may'],

       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular','feb'],

       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular','may'],

       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular','may'],

       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular','apr'],

       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'admin.', 'married', 264.0, 'yes', 'no', 'cellular', 'apr'],

       [36.0, 'technician', 'married', 1109.0, 'no', 'no', 'cellular','aug'],

       [20.0, 'student', 'single', 502.0, 'no', 'no', 'cellular', 'apr'],

       [31.0, 'blue-collar', 'married', 360.0, 'yes', 'yes', 'cellular','jan'],

       [40.0, 'management', 'married', 194.0, 'no', 'yes', 'cellular','aug'],

       [56.0, 'technician', 'married', 4073.0, 'no', 'no', 'cellular','aug'],

       [37.0, 'admin.', 'single', 2317.0, 'yes', 'no', 'cellular', 'apr'],

       [25.0, 'blue-collar', 'single', -221.0, 'yes', 'no', 'unknown','may'],

       [31.0, 'services', 'married', 132.0, 'no', 'no', 'cellular','jul']], dtype=object)

In [ ]:
# @title Task 1
# Finding unique values from the employment column
np.unique(banking_array[:,1])

array(['admin.', 'blue-collar', 'entrepreneur', 'management',
       'self-employed', 'services', 'student', 'technician', 'unemployed'],
      dtype=object)

In [ ]:
# @title Task 2
# Find the count of customers who has taken a personal loan
cust_with_perosnal_loan = (banking_array[:,4] == 'yes')
#print(banking_array[cust_with_perosnal_loan])
np.count_nonzero(cust_with_perosnal_loan)

13

In [ ]:
# @title Task 3
# Find the count of cutomers who has connection and has taken car loan
connection = (banking_array[:,6] == 'cellular')
car_loan = (banking_array[:,5] == 'yes')
merged_cond = (connection) & (car_loan)
np.count_nonzero(merged_cond)

4

In [ ]:
# @title Task 4
# Find the count of customers with personal loan and are married and has car loan
cust_with_perosnal_loan = (banking_array[:,4] == 'yes')
married = (banking_array[:,2] == 'married')
car_loan = (banking_array[:,5] == 'yes')
merged_cond = (cust_with_perosnal_loan & married & car_loan)
np.count_nonzero(merged_cond)

4

In [ ]:
# @title Task 5
# Find the count of customers whose age is greater than 35 and less than 50 and also find the bank balance of these customers
age = (banking_array[:,0] > 35) & (banking_array[:,0] < 50)
bal = banking_array[:,3]
cond = bal[age]
print("Count of customer whose age is greater than 35 and lesser than 50 are", np.count_nonzero(age))
print("Total Bank Balance of these customers is", cond.sum())

Count of customer whose age is greater than 35 and lesser than 50 are 9
Total Bank Balance of these customers is 13845.0


In [ ]:
# @title task 6
# Find the count of customers whose profession is management and is married and has cellular connection
profession = (banking_array[:,1] == 'management')
married = (banking_array[:,2] == 'married')
cellular = (banking_array[:,6] == 'cellular')
cond = (profession) & (married) & (cellular)
np.count_nonzero(cond)

1

In [ ]:
# @title Task 7
# Find the count who are single but have more than average bank balance
single = (banking_array[:,2] == 'single')
bal = banking_array[:,3]
avg_bal = np.mean(bal)
print("Average bank balance is", avg_bal)
cond = (single) & (bal > avg_bal)
print("Customers with balance greater than the average balance are", np.count_nonzero(cond))

Average bank balance is 1442.0
Customers with balance greater than the average balance are 1


In [ ]:
# @title Task 8
'''
Company has decided to give a bonus of 5% of their account balance to those account holders where age is more than or equal
to 55 years and whose account balance is more than 2000. Calculate the sum of the total bank balance to the account holders
after crediting thier bonus amount.
'''
age = (banking_array[:,0])
balance = (banking_array[:,3])
cond = (age >= 55) & (balance > 2000)
tot_bal = balance[cond]
bonus = 0.05 * tot_bal
adding_bonus = np.sum(tot_bal + bonus)
print("Sum of total bank balance to the account holders after crediting their bonus amount is", adding_bonus)

Sum of total bank balance to the account holders after crediting their bonus amount is 4276.65


In [ ]:
# @title Task 9
'''
Company has decided if the age of the customer is less than 25 then his balance will be credited with 2000
and if it is above then credit 1000.
'''
age = banking_array[:,0]
bal = banking_array[:,3]
cond1 = (age <= 25)
tot_bal_25 = bal[cond1]
bonus1 = 2000 + tot_bal_25
cond2 = (age > 25)
tot_bal_abv_25 = bal[cond2]
bonus2 = 1000 + tot_bal_abv_25
print("Customer total balance below age of 25", np.sum(bonus1))
print("Customer total balance above age of 25", np.sum(bonus2))

Customer total balance below age of 25 4281.0
Customer total balance above age of 25 46559.0


In [ ]:
# Find which month had highest joining
np.unique(banking_array[:,-1], return_counts = True)

(array(['apr', 'aug', 'feb', 'jan', 'jul', 'jun', 'may', 'oct'],
       dtype=object),
 array([5, 3, 1, 1, 1, 1, 7, 1]))

# Pandas

In [ ]:
# @title Series
import numpy as np
import pandas as pd

In [ ]:
# Createing a Simple Series
values = [100,200,300,400,500]
ser = pd.Series(values)
print(ser)

0    100
1    200
2    300
3    400
4    500
dtype: int64


In [ ]:
# Changing Index Value
values = [100,200,300,400,500]
ser = pd.Series(values, index = ['a','b','c','d','e'])
print(ser)

a    100
b    200
c    300
d    400
e    500
dtype: int64


In [ ]:
# DataFrame
values = [100,200,300,400,500]
df = pd.DataFrame(values)
print(df)

     0
0  100
1  200
2  300
3  400
4  500


In [ ]:
# Multiple List into DataFrame
values = [100,200,300,400,500]
name = ['John','Ram','Sam','Sita','Siri']

df = pd.DataFrame([name, values])
# Converting horizontal row format into vertical column format
df_t = df.transpose()
df_t.columns = ['Name', 'Values']
print(df_t)

   Name Values
0  John    100
1   Ram    200
2   Sam    300
3  Sita    400
4  Siri    500


In [ ]:
# Reading CSV file into a DataFrame
import pandas as pd
df = pd.read_csv('Titanic.csv')
df

PassengerId  Survived  Pclass  \
0            1.0       0.0     3.0   
1            2.0       1.0     1.0   
2            3.0       1.0     3.0   
3            4.0       1.0     1.0   
4            5.0       0.0     3.0   
..           ...       ...     ...   
994          NaN       NaN     NaN   
995          NaN       NaN     NaN   
996          NaN       NaN     NaN   
997          NaN       NaN     NaN   
998          NaN       NaN     NaN   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0    1.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                               Heikkinen, Miss. Laina  female  26.0    0.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                             Allen, Mr. William Henry    male  35.0    0.0   
..                                                 ...     ...   ...    ...   
994                                                NaN     NaN   NaN    NaN   
995                                                NaN     NaN   NaN    NaN   
996                                                NaN     NaN   NaN    NaN   
997                                                NaN     NaN   NaN    NaN   
998                                                NaN     NaN   NaN    NaN   

     Parch            Ticket     Fare Cabin Embarked  
0      0.0         A/5 21171   7.2500   NaN        S  
1      0.0          PC 17599  71.2833   C85        C  
2      0.0  STON/O2. 3101282   7.9250   NaN        S  
3      0.0            113803  53.1000  C123        S  
4      0.0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
994    NaN               NaN      NaN   NaN      NaN  
995    NaN               NaN      NaN   NaN      NaN  
996    NaN               NaN      NaN   NaN      NaN  
997    NaN               NaN      NaN   NaN      NaN  
998    NaN               NaN      NaN   NaN      NaN  

[999 rows x 12 columns]

In [ ]:
# Shape function
df.shape
# Rows
df.shape[0]
# Columns
df.shape[1]

12

In [ ]:
# To get the size of the dataset
df.size

11988

In [ ]:
# Describe Function
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
# Indexing of columns
df['Age'].min()
# Aggregation functions are max,min,mean and sum

0.42

In [ ]:
# Data preprocessing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(7), object(5)
memory usage: 93.8+ KB


In [ ]:
# Checking the null values
df.isnull()
df.isnull().sum()

PassengerId    108
Survived       108
Pclass         108
Name           108
Sex            108
Age            285
SibSp          108
Parch          108
Ticket         108
Fare           108
Cabin          795
Embarked       110
dtype: int64

In [ ]:
# Eliminating all the null values
df.dropna(how = 'all', inplace = True) # how = 'all' (removing all null values if the entire row is null)
# how = 'any'  (removing entire row if any one cell is null)

In [ ]:
# Checking the datatype of the columns
df['Age'].dtype

dtype('float64')

In [ ]:
# Checking the memory usage
df['PassengerId'].memory_usage()

8910

In [ ]:
# changing the datatype
df['PassengerId'] = df['PassengerId'].astype('int16')

In [ ]:
# Printing the preview of the dataset
df.head() # Printing first 5 rows
df.head(10) # Printing first 10 rows
df.head(-5) # Print all the rows except the last 5 rows

PassengerId  Survived  Pclass  \
0              1       0.0     3.0   
1              2       1.0     1.0   
2              3       1.0     3.0   
3              4       1.0     1.0   
4              5       0.0     3.0   
..           ...       ...     ...   
881          882       0.0     3.0   
882          883       0.0     3.0   
883          884       0.0     2.0   
884          885       0.0     3.0   
885          886       0.0     3.0   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0    1.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                               Heikkinen, Miss. Laina  female  26.0    0.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                             Allen, Mr. William Henry    male  35.0    0.0   
..                                                 ...     ...   ...    ...   
881                                 Markun, Mr. Johann    male  33.0    0.0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0    0.0   
883                      Banfield, Mr. Frederick James    male  28.0    0.0   
884                             Sutehall, Mr. Henry Jr    male  25.0    0.0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0    0.0   

     Parch            Ticket     Fare Cabin Embarked  
0      0.0         A/5 21171   7.2500   NaN        S  
1      0.0          PC 17599  71.2833   C85        C  
2      0.0  STON/O2. 3101282   7.9250   NaN        S  
3      0.0            113803  53.1000  C123        S  
4      0.0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
881    0.0            349257   7.8958   NaN        S  
882    0.0              7552  10.5167   NaN        S  
883    0.0  C.A./SOTON 34068  10.5000   NaN        S  
884    0.0   SOTON/OQ 392076   7.0500   NaN        S  
885    5.0            382652  29.1250   NaN        Q  

[886 rows x 12 columns]

In [ ]:
df.tail() # Printing last 5 rows
df.tail(10) # Printing last 10 rows
df.tail(-10)

PassengerId  Survived  Pclass                                      Name  \
10            11       1.0     3.0           Sandstrom, Miss. Marguerite Rut   
11            12       1.0     1.0                  Bonnell, Miss. Elizabeth   
12            13       0.0     3.0            Saundercock, Mr. William Henry   
13            14       0.0     3.0               Andersson, Mr. Anders Johan   
14            15       0.0     3.0      Vestrom, Miss. Hulda Amanda Adolfina   
..           ...       ...     ...                                       ...   
886          887       0.0     2.0                     Montvila, Rev. Juozas   
887          888       1.0     1.0              Graham, Miss. Margaret Edith   
888          889       0.0     3.0  Johnston, Miss. Catherine Helen "Carrie"   
889          890       1.0     1.0                     Behr, Mr. Karl Howell   
890          891       0.0     3.0                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
10   female   4.0    1.0    1.0     PP 9549  16.7000    G6        S  
11   female  58.0    0.0    0.0      113783  26.5500  C103        S  
12     male  20.0    0.0    0.0   A/5. 2151   8.0500   NaN        S  
13     male  39.0    1.0    5.0      347082  31.2750   NaN        S  
14   female  14.0    0.0    0.0      350406   7.8542   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
886    male  27.0    0.0    0.0      211536  13.0000   NaN        S  
887  female  19.0    0.0    0.0      112053  30.0000   B42        S  
888  female   NaN    1.0    2.0  W./C. 6607  23.4500   NaN        S  
889    male  26.0    0.0    0.0      111369  30.0000  C148        C  
890    male  32.0    0.0    0.0      370376   7.7500   NaN        Q  

[881 rows x 12 columns]